- dnsperf.c
> Fix min/max latency summing for multithreaded runs

- dnsperf.c
> fix calculation of per_thread socket counts

- contrib/queryparse/queryparse
- datafile.c
- datafile.h
- dns.c
- dns.h
- dnsperf.c
- opt.c
- os.c
- os.h
- resperf.c
- util.h
> Infrastructure services master

- README.md
> Add deb based distros dependencies

- .clang-format
- fmt.sh
- src/datafile.c
- src/datafile.h
- src/dns.c
- src/dns.h
- src/dnsperf.c
- src/log.c
- src/log.h
- src/net.c
- src/net.h
- src/opt.c
- src/opt.h
- src/os.c
- src/os.h
- src/resperf.c
- src/util.h
> Clang format

- contrib/queryparse/queryparse
- src/dnsperf.c
- src/net.c
- Fix LGTM alerts and SonarCloud issues
> LGTM, SonarCloud

- src/net.c
- Fix check for having more DNS messages in the receive buffer for TCP and TLS
> recvbuf have more

- src/dnsperf.c
- src/net.c
- src/resperf.c
- Fix #63: Treat connection reset/closed error for TCP connections as try again
> connection

- rpm/dnsperf.spec
- Fix include search path for openSUSE Tumbleweed
> openSUSE Tumbleweed

- src/Makefile.am
- src/dnsperf.c
- src/list.h
- src/resperf.c
- Issue #73: Remove dependency on ISC's linked list functions
> ISC linked list

- src/datafile.c
- src/dns.c
- src/dnsperf.c
- src/net.c
- src/os.c
- src/resperf.c
- src/result.h
- Issue #73: Actually transition `isc_result_t`
> isc_result_t

- configure.ac
- src/dns.c
- src/dns.h
- src/dnsperf.c
- src/resperf.c
- src/test/test2.sh
- Issue #73:
- Disable ISC HMAC code
- Disable HMAC tests
> Disable HMAC

- src/datafile.c
- src/dns.c
- src/dns.h
- src/dnsperf.c
- src/log.c
- src/log.h
- src/net.c
- src/opt.c
- src/os.c
- src/resperf.c
- src/strerror.c
- src/strerror.h
- src/util.h
- Issues #73:
- Disable dynamic update code
- Disable EDNS option code
- Remove unused struct members
- Rearrange include headers
> dynamic updates, edns, headers

- src/datafile.c
- src/dns.c
- src/dnsperf.c
- src/log.c
- src/resperf.c
- src/util.h
- Fix namespace collision issue with macros
> Namespace clash

- src/dns.c
- src/dnsperf.c
- src/resperf.c
- src/test/test2.sh
- Issue #73:
- Remove `isc_mem_` functions
- Disable EDNS tests
> ISC mem, tests

- src/dns.c
- src/dns.h
- src/dnsperf.c
- src/resperf.c
- Issue #73: Remove most of ISC library dependencies
> ISC dependencies

- src/dns.c
- src/gen-qtype.c.py
- src/test/test2.sh
- src/test/test3.sh
- Issue #73: Re-implement EDNS0 support
- Use HTTPS to fetch IANA DNS parameters CSV
> EDNS, https

- src/tsig.c
- Fix scan-build/sonarcloud false-positive
> Sonarcloud

- .lgtm.yml
- .travis.yml
- README.md
- configure.ac
- debian/control
- rpm/dnsperf.spec
- src/Makefile.am
- src/buffer.h
- src/dns.c
- src/dns.h
- src/dnsperf.c
- src/resperf.c
- src/result.h
- src/test/test2.sh
- src/tsig.c
- Fix #73:
- Re-implement dynamic update using LDNS
- Update dependencies for LGTM, Travis, packages and README
- TSIG: Check for failure when parsing or adding the TSIG name and algorithm
> BIND dependency

- src/dnsperf.1.in
- src/resperf.1.in
> man-page format

- src/test/Makefile.am
- src/test/test5.sh
- Add network tests that triggers reconnection
> network tests

- src/dns.c
- src/test/test2.sh
- `dns`: Add check when labels + label lengths goes over 255
> Fix too long name

- src/resperf.c
- `resperf`: Initiate buckets earlier because events can be called immediately from opensocket
> resperf buckets

- src/net_doh.c
- `doh`:
- Reconnect if session send fails in sendto
- Reconnect if RST_STREAM or GOAWAY is received
> DoH reconnect

- src/net_doh.c
- `doh`:
- Add default initial value for max concurrent streams
- Tweak checking if there is still queries to be sent
> DoH sending

- src/test/test5.sh
- Kill existing `dumdumd` processes before running tests
> Tests with dumdumd

- src/dnsperf.c
> Fix first call to diff_stats

- src/dnsperf.1.in
- src/dnsperf.c
> Fix dnsperf -Q to not overshot target value

- src/dnsperf.c
- `dnsperf`: Fix #258: Move TSIG context to each sending thread
> TSIG context per thread
