.lgtm.yml
.travis.yml
README.md
configure.ac
src/Makefile.am
src/datafile.c
src/dns.c
src/dnsperf.c
src/opt.c

- Add Travis CI
- Enable building via buildbot
- Add LGTM configuration
- Handle bind library changes to HMAC (see #22) and other differences between versions
- Workaround issue on FreeBSD (see #23)
- Clang `scan-build` fixes
- Use `snprintf()` and OpenBSD's `strlcat()`
- Add build dependencies for CentOS, FreeBSD and OpenBSD

CI, buildbot

---

src/dnsperf.c
src/resperf.c

It seems an unintetional fallout from c27afd4218b5.

remove visible "u" characters after numbers

---

src/datafile.c
src/dnsperf.1.in
src/dnsperf.c
src/net.c
src/net.h
src/os.c
src/os.h
src/resperf.1.in
src/resperf.c

- Add TCP support
- Rework sock structure to include a mode
- Add mode for file, pipe, UDP and TCP
- Add `perf_net_*` functions to handle sock things, such as sending and receiving
- Use sock structure in `perf_os_*` functions
- Add `perf_os_waituntilanywritable()`
- `dnsperf`: Add `-m` for setting transport mode, UDP or TCP
- `resperf`: Add `-M` for setting transport mode, UDP or TCP

TCP support

---

src/dnsperf.c
src/net.c
src/net.h
src/resperf.c

- `net`: Handle continue sending for TCP, if not all was sent
- `dnsperf`:
- Handle sending in progress
- Make sure ready check loop can't run forever
- `resperf`:
- Handle sending in progress

TCP send, socket ready loop

---

configure.ac
fmt.sh
src/Makefile.am
src/datafile.c
src/dns.c
src/dnsperf.c
src/net.c
src/net.h
src/resperf.c

- Close #71: Pull @pemensik changes to add other
- Fix #67: Workaround for BIND 9.16
- Fix #23: Remove use of static libcrypto
- Update formatting based on latest `clang-format`

BIND, libcrypto, clang format

---

configure.ac

- `configure`: Fix usage of `AS_VAR_APPEND()`

AS_VAR_APPEND

---

src/Makefile.am
src/datafile.c
src/dns.c
src/dns.h
src/dnsperf.c
src/list.h
src/net.c
src/opt.c
src/os.c
src/os.h
src/resperf.c
src/result.h

- Issue #73:
- Transition `isc_result_t` to `perf_result_t` using temporary mapping
- Add `perf_result_totext()` as temporary macro which calls `isc_result_totext()`

isc_result_t

---

src/datafile.c
src/datafile.h
src/dnsperf.c
src/resperf.c

- `datafile`:
- Issues #73: Remove ISC library dependency when reading datafiles
- Remove usage of `ISC_TRUE` and `ISC_FALSE`
- `dnsperf`: Fix potential memory leak of query descriptions when using verbose

datafile, query desc

---

README.md
configure.ac
debian/control
rpm/dnsperf.spec
src/Makefile.am
src/dns.c
src/gen-qtype.c.py
src/os.c
src/qtype.c
src/qtype.h

- Issue #73:
- Re-implement `name_fromstring()`
- Implement `qtype_fromstring()`
- Add QTYPE table generator based on IANA DNS parameters CSV
- Remove BIND as a dependency!
- Rework `perf_result_t`
- Remove BIND and BIND's dependencies from configure and packages
- Update README

BIND dependency

---

configure.ac
src/dnsperf.1.in
src/dnsperf.c
src/net.c
src/opt.c
src/resperf.c
src/test/test2.sh

- Fix Sonarcloud issue:
- `net`: Check for and use `TLS_method`
- `net`: Only use TLS v1.2 and above versions
- `opt`: Remove usage of `strcat()` and `strlcat()`
- `opt`: Use safer `strncpy()`
- Use DoT alongside TLS
- Add "dot" to `dnsperf -m` and `resperf -M` option
- Update documentation

DOT, TLS version, Sonarcloud

---

src/dns.c
src/dnsperf.c
src/log.c
src/log.h
src/net.c
src/resperf.c
src/test/datafile3
src/test/test2.sh
src/test/test3.sh

- `dns`: Add more check for parsing domain names to wire
- `log`: Add option `-W` for outputting warnings and errors to stdout
- Improve coverage and tests
- Run network tests using IPv6

Checks, coverage, log, test IPv6

---

contrib/queryparse/queryparse

Queryparse now ends with error in python3. And cannot be interrupted, when it is parsing. Following commits fixes that.

Fix few python3 issues in queryparse

---

src/resperf.c

- `resperf`:
- Fix #129: Move reading of next line to after finding a place for it, otherwise line would be lost and lead to `ran out of data`
- Increase buffer for reading input lines

ran out of data

---

src/datafile.c
src/resperf.c

- `resperf`: Fix #88: Move socket ready check to before reading from datafile

resperf TLS

---

src/resperf.c

- `resperf`: Fix potential buffer overrun when using response qid for `queries[]`

Response qid to index

---

src/dnsperf.1.in
src/opt.c
src/opt.h
src/resperf.1.in
src/resperf.c

- Update man-pages
- `opt`: Add new type for zero or positive integers
- `resperf`:
- Add default value to `-C`
- Add new option `-R`: reopen datafile on end, allow for infinit use of it
- Add new option `-F n`: the maximum number of queries that is allowed to fall behind, zero to disable
- Try and process more request each run to hopefully not hit max outstanding so easy when high QPS

man-page, opts, tuneups

---

src/resperf.c
src/test/test3.sh

- `resperf`: Fix #155: Add `-E` to set EDNS option

edns option

---

src/dnsperf.1.in
src/dnsperf.c
src/net.h
src/net_doh.c
src/resperf.1.in
src/resperf.c

- `doh`:
- Use outstanding queries as concurrent streams limit
- Fix return len from receiving which was showing incorrect response sizes

DoH concurrent streams

---

src/dnsperf.1.in
src/dnsperf.c
src/net.h
src/net_doh.c
src/net_dot.c
src/net_tcp.c
src/resperf.c

- Fix #195: Add `-O num-queries-per-conn=<num>` to control number of queries sent over a connection before re-connecting

Queries per connection

---

src/dnsperf.c

- `dnsperf`: Make sure `num_outstanding()` don't return negative numbers, happens if queries are timed out before being sent

Negative outstanding

---

src/dnsperf.c

- `dnsperf`: Issue #208:
- `recv_one()`: Fix handling errno, only store EAGAIN if no other error has been received
- `do_recv()`: Don't break on error as it will count it as a received message

Receive socket error handling

---

src/dnsperf.1.in
src/dnsperf.c
src/opt.c

Handy for diagnosing situations when a server responds all the time but starts SERVFAILing at some point in the middle of the test.

verbose interval stats for dnsperf

---

src/dnsperf.c

- `dnsperf`: Fix #222: don't process unexpected message if the message is suppressed

Suppress unexpected

---

src/dnsperf.1.in
src/dnsperf.c
src/net.c
src/net.h
src/net_doh.c
src/net_dot.c
src/resperf.c

Support for the TLS SNI extension when querying with DNS-over-HTTPS or DNS-over-TLS.
Otherwise some TLS servers (like cloudflare gateway) respond with 'Handshake Failure' instead of the server hello. When passing the '-v' flag to resperf, it logs: `Warning: failed to send packet: socket 0 not ready`.
This is solved with a new command line argument: `-O tls-sni=example.org`, as I tested on AlmaLinux for both DoT and DoH.
TODO:

Add TLS Server Name Indication extension support

---

src/dnsperf.c

- `dnsperf`: Fix thread name length, glibc is limited to 16 characters

Thread names
